### PR TITLE
Add info to upload to Zenodo

### PR DESCRIPTION
**Pull request by ehsteve**

### CODE REVIEW

**Comment by ehsteve** [comment]
FYI, highly modeled off of the astropy APE readme.

**Comment by ehsteve** [comment]
thanks for the review @astrofrog!

**Comment by mbobra** [comment]
I suggest we also add the `version` keyword (this will supplement the `related_identifiers` value, which, from what I understand of the description, defaults to the most recent version).

We can also add the `keywords` keyword and populate it with values like "affiliated packages", "physical units", or "governance" in case we want these SEPs to be more searchable.

**Comment by mbobra** [comment]
@ehsteve Can you upload to Zenodo so I can cite the SEPs in the paper?

**Comment by ehsteve** [comment]
Working on it and hopefully should have it done by today. Spending some time cleaning up the SEPs before they are officially published!

**Pull request merged**
