### PR TITLE
Code of Conduct

### PR DESCRIPTION
**Pull request by dpshelio**
Here is a text I've composed mixing the PSF formatting with the astropy content.

Let's discuss!!

### CODE REVIEW

**Comment by tiagopereira** [comment]
I'm not an active developer but follow Sunpy with interest. Thank you for the draft version @dpshelio. 

I feel that the current version is too long. My preference in these things is to keep it short and simple, and in this case it seems to have extended both Astropy's and PSF's versions. Here are a few detailed comments:

- I don't like the second part of the "Respectful" paragraph, starting with "We provide a harassment- and bullying-free environment (...)", which seems copied from Astropy. First, I don't see SunPy providing an environment -- we are not a business. Second, listing all the forms of discrimination and particular "faults" seems excessive and reads like a race to find which project can be more politically correct.
- the sentence "Overall, we are good to each other (...)" seems too exhaustive and excessive. I suggest removing it.
- The wording on PSFs part on reporting violations of the code also seems a lot more elegant and appropriate for this kind of open source projects, while Astropy's version reads like it was taken from a corporation handbook. 

Overall, I feel that if the PSF, being a much larger organisation, can do with a more condensed and concise CoC, so can SunPy. It's hard to justify why SunPy should have such a long one.

**Comment by ehsteve** [comment]
Good example by github. See https://help.github.com/articles/github-community-guidelines/

**Comment by ehsteve** [comment]
For reference here is the Astropy code of conduct http://www.astropy.org/about.html#codeofconduct

**Comment by dpshelio** [comment]
@tiagopereira - I do agree completely with your comments. I find the PSF a lot more direct, easier to read and *less scary*. The one from Astropy makes me think twice everything I do/write, which is not necessarily bad, but kind of stops me of being who I am in some way (no, I'm not a bully, though I take a lot of stuff less seriously than others).

**Comment by ayshih** [comment]
Maybe I'm off on a different philosophical road, but it seems to me that this SEP shouldn't be laying out the text of the code of conduct (CoC), but instead describing the *logistics* of the CoC (which are completely missing from this SEP): that we'll have a CoC with certain required elements, that we'll have a person/committee receiving confidential@sunpy.org emails, how we'll judge and enforce CoC violations, etc.  Other thoughts:

* I feel that this CoC is far too long and detailed, and should be cut in half, if not more.  In my opinion, even PSF's CoC is still too long.
* Obviously, we'll need a functional confidential@sunpy.org (both technically and operationally) before we can publish this CoC.

**Comment by ehsteve** [comment]
Closed as dealt with in #23.

**Pull request closed without merging**
